model_selection:
  module_0:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      random_state: 42
    search_param_grid:
      n_estimators: [100, 200]  # Reduce range
      learning_rate: [0.1]  # Fixed learning rate
      max_depth: [3, 5]  # Smaller range for depth
      min_samples_split: [2, 4]
      min_samples_leaf: [1, 3]
      subsample: [0.9, 1.0]  # Fewer values

  module_1:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      random_state: 42
    search_param_grid:
      n_estimators: [50, 100]
      learning_rate: [0.1, 1.0]  # Fixed learning rates
      algorithm: ['SAMME.R']  # Focus on the faster algorithm

  module_2:
    class: XGBClassifier
    module: xgboost.sklearn
    params:
      random_state: 42
    search_param_grid:
      n_estimators: [100, 200]
      learning_rate: [0.1]  # Focus on one value
      max_depth: [3, 5]
      min_child_weight: [1, 3]
      subsample: [0.9, 1.0]
      colsample_bytree: [0.9]
      gamma: [0, 0.1]  # Smaller range
      scale_pos_weight: [1, 10]
