grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 2
    verbose: 2

model_selection:
  module_0:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      random_state: 42  # Example static parameter; can be left empty if not needed
    search_param_grid:
      n_estimators: [100, 200]
      learning_rate: [0.01, 0.1]
      max_depth: [3, 5, 7]
      min_samples_split: [2, 4, 6]
      min_samples_leaf: [1, 3, 5]
      subsample: [0.8, 0.9]

  module_1:
    class: AdaBoostClassifier
    module: sklearn.ensemble
    params:
      random_state: 42  # Example static parameter
    search_param_grid:
      n_estimators: [50, 100]
      learning_rate: [0.01, 0.1]
      algorithm: ['SAMME', 'SAMME.R']

  module_2:
    class: XGBClassifier
    module: xgboost.sklearn
    params:
      random_state: 42  # Example static parameter
    search_param_grid:
      n_estimators: [100, 200]
      learning_rate: [0.01, 0.1]
      max_depth: [3, 5, 7]
      min_child_weight: [1, 3]
      subsample: [0.8, 0.9]
      colsample_bytree: [0.8, 0.9]
      gamma: [0, 0.1, 0.2]
      scale_pos_weight: [1, 10]
