columns:
  - Timestamp: object
  - Age: int
  - Gender: object
  - Country: object
  - self_employed: object
  - family_history: object
  - treatment: object
  - work_interfere: object
  - no_employees: object
  - remote_work: object
  - tech_company: object
  - benefits: object
  - care_options: object
  - wellness_program: object
  - seek_help: object
  - anonymity: object
  - leave: object
  - mental_health_consequence: object
  - phys_health_consequence: object
  - coworkers: object
  - supervisor:  object
  - mental_health_interview: object
  - phys_health_interview: object
  - mental_vs_physical: object
  - obs_consequence: object
  - state: object
  - comments: object

numerical_columns:
 - Age


categorical_columns:
  - Timestamp
  - comments
  - Gender
  - self_employed
  - family_history
  - Country
  - treatment
  - work_interfere
  - no_employees
  - remote_work
  - tech_company
  - benefits
  - care_options
  - wellness_program
  - seek_help
  - anonymity
  - leave
  - mental_health_consequence
  - phys_health_consequence
  - coworkers
  - supervisor
  - mental_health_interview
  - phys_health_interview
  - mental_vs_physical
  - obs_consequence
  - state

drop_columns:
  - Timestamp
  - comments
  - state
  - Country


lb_en_columns:
  - 'work_interfere'
  - 'no_employees'
  - 'benefits'
  - 'care_options'
  - 'wellness_program'
  - 'seek_help'
  - 'anonymity'
  - 'leave'
  - 'mental_health_consequence'
  - 'phys_health_consequence'
  - 'coworkers'
  - 'supervisor'
  - 'mental_health_interview'
  - 'phys_health_interview'
  - 'mental_vs_physical'
  - 'obs_consequence'
  - 'Gender'
  - 'self_employed'
  - 'remote_work'
  - 'tech_company'
  - 'family_history'


data_null_handler:
  Gender:
    - Male
  work_interfere:
    - Don't know
  no_employees:
    - 26-100
  benefits:
    - Don't know
  care_options:
    - Not sure
  wellness_program:
    - Don't know
  seek_help:
    - Don't know
  anonymity:
    - Don't know
  leave:
    - Don't know
  mental_vs_physical:
    - Don't know
  self_employed:
    - "Yes"





transform_columns:
 - Age
  



